#!/usr/bin/env python3
"""freeze_snapshot — capture the current state of every reproducibility layer
into a manifest YAML. Generates `reproducibility/captured/manifest-<date>-<runid>.yaml`
from the template at `reproducibility/manifest-template.yaml`.

Usage:
    python scripts/freeze_snapshot.py --purpose "R1.5 Omni tamoxifen baseline"
    python scripts/freeze_snapshot.py --purpose "..." --pod-provider runpod --pod-id fqi5lcbn22pl9o

What it captures (best-effort; degrades gracefully when a probe fails):
  - Local: git repo SHA + dirty flag, hostname, user
  - Remote pod (if --pod-provider given): driver, CUDA, GPU type, docker version, container digests
  - Repo artifacts: rubric SHAs, fixture SHAs, OpenEM commit, graph artifact SHA if present
  - simple-evals SHA (read from third_party/simple-evals/.git/HEAD if vendored)

It does NOT execute the bench. It records "what we'd run." Pair with
freeze_verify_all.py at result-write time to record "what we actually ran."

NOTE: This is intentionally side-effect-free except for the manifest YAML it
emits. It does NOT modify any pod state, does NOT pull docker images, and does
NOT touch the .env. Read-only by design.
"""

from __future__ import annotations

import argparse
import getpass
import hashlib
import json
import os
import platform
import socket
import subprocess
import sys
import time
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TEMPLATE = REPO / "reproducibility" / "manifest-template.yaml"
CAPTURED = REPO / "reproducibility" / "captured"


def _sha256_of_path(path: Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _git(*args: str, cwd: Path = REPO) -> str | None:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(cwd), *args], stderr=subprocess.DEVNULL, text=True
        )
        return out.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _git_dirty(cwd: Path = REPO) -> bool:
    out = _git("status", "--porcelain", cwd=cwd)
    return bool(out)  # any output = dirty


def _ssh_probe(host: str, cmd: str, ssh_args: list[str] | None = None, timeout: int = 20) -> str | None:
    args = ["ssh", "-o", f"ConnectTimeout={timeout}"]
    if ssh_args:
        args.extend(ssh_args)
    args.extend([host, cmd])
    try:
        out = subprocess.check_output(args, stderr=subprocess.DEVNULL, text=True, timeout=timeout + 5)
        return out.strip()
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
        return None


def _read_simple_evals_pin() -> str | None:
    """Read the pinned simple-evals SHA from third_party clone if present."""
    head_path = REPO / "third_party" / "simple-evals" / ".git" / "HEAD"
    if not head_path.exists():
        return None
    head = head_path.read_text().strip()
    if head.startswith("ref:"):
        ref_path = REPO / "third_party" / "simple-evals" / ".git" / head.split(" ", 1)[1]
        if ref_path.exists():
            return ref_path.read_text().strip()
        return None
    return head


def _yaml_dump(data: dict, out_path: Path) -> None:
    """Minimal-dependency YAML dump; we use json + a header to avoid needing pyyaml here."""
    # If pyyaml is available, prefer it for human-readable output.
    try:
        import yaml  # type: ignore
        with out_path.open("w") as f:
            f.write("# Generated by scripts/freeze_snapshot.py\n")
            yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)
        return
    except ImportError:
        pass
    # Fallback: emit JSON with a header. Still valid YAML.
    with out_path.open("w") as f:
        f.write("# Generated by scripts/freeze_snapshot.py (JSON-as-YAML fallback)\n")
        json.dump(data, f, indent=2, default=str)
        f.write("\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--purpose", required=True, help="free-form description of the run")
    parser.add_argument("--fixture", default="corpus/clinical-demo/CLN-DEMO-TAMOXIFEN-MIRENA")
    parser.add_argument("--pod-provider", default=None, choices=["brev", "runpod", None])
    parser.add_argument("--pod-host", default=None, help="ssh host alias (e.g., warm-lavender-narwhal, runpod-prism)")
    parser.add_argument("--pod-id", default=None, help="provider-side pod id")
    parser.add_argument("--ssh-config", default=None, help="path to project-local ssh config (-F)")
    parser.add_argument("--out-dir", default=str(CAPTURED))
    args = parser.parse_args()

    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    run_id = uuid.uuid4().hex[:8]
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    session_id = f"medomni-{time.strftime('%Y%m%d-%H%M%S', time.gmtime())}-{run_id}"

    manifest: dict = {
        "session": {
            "id": session_id,
            "date": now,
            "purpose": args.purpose,
            "fixture_used": args.fixture,
        }
    }

    # Layer 1 — bare metal (probed if pod given)
    bare_metal: dict = {
        "cuda_toolkit": "13.2",
        "pod_provider": args.pod_provider,
        "pod_id": args.pod_id,
    }
    ssh_args = ["-F", args.ssh_config] if args.ssh_config else None
    if args.pod_host:
        host = args.pod_host
        bare_metal["pod_host"] = host
        bare_metal["driver_version"] = _ssh_probe(
            host, "nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1", ssh_args
        )
        bare_metal["gpu_type"] = _ssh_probe(
            host, "nvidia-smi --query-gpu=name --format=csv,noheader | head -1", ssh_args
        )
        bare_metal["gpu_count"] = _ssh_probe(host, "nvidia-smi -L | wc -l", ssh_args)
    manifest["bare_metal"] = bare_metal

    # Layer 2 — container runtime
    container_runtime: dict = {}
    if args.pod_host:
        container_runtime["docker_version"] = _ssh_probe(args.pod_host, "docker --version 2>&1", ssh_args)
    manifest["container_runtime"] = container_runtime

    # Layer 3 — GPU stack (best-effort)
    manifest["gpu_stack"] = {
        "cudnn": None,
        "cuvs": None,
        "rapids": None,
        "nx_cugraph": None,
    }

    # Layer 4 — inference container (filled at deploy time, not capture time)
    manifest["inference"] = {
        "serve_image": None,
        "serve_image_resolved_tag": "vllm/vllm-openai:v0.20.0",
    }

    # Layer 5 — model revisions (filled at deploy/load time)
    manifest["models"] = {
        "inference": {
            "id": "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-NVFP4",
            "revision": None,
        },
        "embedding": {"id": "nvidia/NV-Embed-v2", "revision": None},
        "rerank": {"id": "nvidia/llama-3.2-nv-rerankqa-1b-v2", "revision": None},
        "guard": {"id": "meta-llama/Llama-Guard-3-8B", "revision": None},
        "judge": {"id": None, "revision": None},
    }

    # Layer 6 — corpora + graph
    openem_path = Path("/Users/kiteboard/openem-corpus")
    openem_commit = _git("rev-parse", "HEAD", cwd=openem_path) if openem_path.exists() else None
    graph_artifact = REPO / "data" / "lazygraph" / "openem_370_persona_tagged_v1.gpickle"
    manifest["corpus"] = {
        "openem": {
            "repo": "GOATnote-Inc/openem-corpus",
            "commit": openem_commit,
            "file_count": 370,
        },
        "pubmed_oa": {"snapshot_date": None, "file_count": None},
    }
    manifest["graph"] = {
        "build_artifact_path": str(graph_artifact.relative_to(REPO)) if graph_artifact.exists() else None,
        "build_artifact_sha": _sha256_of_path(graph_artifact),
        "node_count": None,
        "edge_count": None,
        "leiden_resolution": 0.5,
    }

    # Layer 7 — eval framework
    fixture_dir = REPO / args.fixture
    rubric_path = fixture_dir / "rubric.json"
    case_path = fixture_dir / "case.json"
    ideal_path = fixture_dir / "ideal-answer.md"
    manifest["eval"] = {
        "rubric_id": "CLN-DEMO-TAMOXIFEN-MIRENA-v1",
        "rubric_sha": _sha256_of_path(rubric_path),
        "fixture_sha": _sha256_of_path(case_path),
        "ideal_answer_sha": _sha256_of_path(ideal_path),
        "scoring_math": {
            "library": "openai/simple-evals",
            "commit": _read_simple_evals_pin() or "ee3b0318d8d1d9d72755a4120879be65f7c07e9e",
            "primitives_used": ["RubricItem", "calculate_score", "GRADER_TEMPLATE"],
        },
        "n_trials": 3,
    }

    # Layer 8 — sampling
    manifest["sampling"] = {
        "seed": 42,
        "temperature": 0.6,
        "top_p": None,
        "top_k": None,
        "max_tokens": 1024,
        "thinking_token_budget": 16384,
        "enable_thinking": True,
    }

    # Layer 9 — result (filled post-bench)
    manifest["result"] = {
        "artifact_json_path": None,
        "artifact_json_sha": None,
        "card_md_path": None,
        "card_md_sha": None,
        "rubric_score_mean": None,
        "rubric_score_hw95": None,
    }

    # Audit envelope
    manifest["audit"] = {
        "captured_by": "freeze_snapshot.py",
        "captured_at": now,
        "cli_user": getpass.getuser(),
        "hostname": socket.gethostname(),
        "platform": platform.platform(),
        "git_repo_sha": _git("rev-parse", "HEAD"),
        "git_repo_dirty": _git_dirty(),
        "notes": "",
    }

    manifest["drift_policy"] = {
        "on_drift": "halt",
        "allow_drift_layers": [],
        "allow_drift_commit_message_marker": "[allow-drift-reason:",
    }

    # Write the manifest
    out_path = out_dir / f"manifest-{session_id}.yaml"
    _yaml_dump(manifest, out_path)
    print(f"wrote {out_path}")
    print(f"  session_id: {session_id}")
    print(f"  fixture:    {args.fixture}")
    print(f"  rubric_sha: {manifest['eval']['rubric_sha'][:16] if manifest['eval']['rubric_sha'] else 'MISSING'}")
    print(f"  repo_sha:   {manifest['audit']['git_repo_sha'][:8] if manifest['audit']['git_repo_sha'] else 'MISSING'}{' DIRTY' if manifest['audit']['git_repo_dirty'] else ''}")
    print(f"  pod_host:   {bare_metal.get('pod_host', 'not probed')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
